# Generated by Django 4.1.7 on 2023-05-14 12:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
