# Generated by Django 4.1.7 on 2023-06-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0007_myobject_locationofworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myobject',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='myobject',
            name='types',
        ),
        migrations.DeleteModel(
            name='LocationOfWorks',
        ),
        migrations.DeleteModel(
            name='MyObject',
        ),
    ]
