# Generated by Django 4.1.7 on 2023-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0009_myobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobject',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myobject',
            name='image',
            field=models.ImageField(upload_to='image_works/%Y/%m/%d/'),
        ),
    ]
