# Generated by Django 4.1.7 on 2023-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0011_locationobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationobjects',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
