# Generated by Django 4.1.7 on 2023-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0012_locationobjects_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationobjects',
            name='image',
            field=models.ImageField(default=None, upload_to='city objects'),
            preserve_default=False,
        ),
    ]
