# Generated by Django 4.1.7 on 2023-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0013_locationobjects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationobjects',
            name='image',
            field=models.ImageField(upload_to='objects'),
        ),
    ]
