# Generated by Django 4.1.7 on 2023-05-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at']},
        ),
    ]
